/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MynaWalletFactoryInterface extends ethers.utils.Interface {
  functions: {
    "computeWalletAddress((bytes,bytes))": FunctionFragment;
    "createWallet((bytes,bytes))": FunctionFragment;
    "mynaWallets(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "computeWalletAddress",
    values: [{ n: BytesLike; e: BytesLike }]
  ): string;
  encodeFunctionData(
    functionFragment: "createWallet",
    values: [{ n: BytesLike; e: BytesLike }]
  ): string;
  encodeFunctionData(
    functionFragment: "mynaWallets",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeWalletAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mynaWallets",
    data: BytesLike
  ): Result;

  events: {
    "Created(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Created"): EventFragment;
}

export type CreatedEvent = TypedEvent<[string] & { mynaWallet: string }>;

export class MynaWalletFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MynaWalletFactoryInterface;

  functions: {
    computeWalletAddress(
      _pubkey: { n: BytesLike; e: BytesLike },
      overrides?: CallOverrides
    ): Promise<[string] & { walletAddr: string }>;

    createWallet(
      _pubkey: { n: BytesLike; e: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mynaWallets(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;
  };

  computeWalletAddress(
    _pubkey: { n: BytesLike; e: BytesLike },
    overrides?: CallOverrides
  ): Promise<string>;

  createWallet(
    _pubkey: { n: BytesLike; e: BytesLike },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mynaWallets(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    computeWalletAddress(
      _pubkey: { n: BytesLike; e: BytesLike },
      overrides?: CallOverrides
    ): Promise<string>;

    createWallet(
      _pubkey: { n: BytesLike; e: BytesLike },
      overrides?: CallOverrides
    ): Promise<string>;

    mynaWallets(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Created(address)"(
      mynaWallet?: string | null
    ): TypedEventFilter<[string], { mynaWallet: string }>;

    Created(
      mynaWallet?: string | null
    ): TypedEventFilter<[string], { mynaWallet: string }>;
  };

  estimateGas: {
    computeWalletAddress(
      _pubkey: { n: BytesLike; e: BytesLike },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createWallet(
      _pubkey: { n: BytesLike; e: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mynaWallets(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    computeWalletAddress(
      _pubkey: { n: BytesLike; e: BytesLike },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createWallet(
      _pubkey: { n: BytesLike; e: BytesLike },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mynaWallets(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
